config/urls.py
from django.contrib import admin
from django.urls import path, include
from notes.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('', home, name='home'),
]

notes/urls.py
from django.urls import path
from . import views


app_name = 'notes'

urlpatterns = [
    path('list/', views.note_list, name='list'),
    path('create/', views.note_create, name='create'),
    path('detail/<int:pk>/', views.note_detail, name='detail'),
]

notes/models.py
from django.db import models


class Notes(models.Model):
    note_title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)

tasks/models.py
from django.db import models

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Notes


def home(request):
    return render(request, 'index.html')

def note_list(request):
    notes = Notes.objects.all()
    ctx = {'notes': notes}
    return render(request, 'notes/list.html', ctx)

def note_create(request):
    if request.method == 'POST':
        note_title = request.POST.get('note_title')
        content = request.POST.get('content')
        if note_title and content:
            Notes.objects.create(
                note_title=note_title,
                content=content,
            )
            return redirect('notes:list')
    return render(request, 'notes/form.html')


def note_detail(request):
    notes = get_object_or_404(request, pk)
    ctx = {'notes': notes}
    return render(request, 'notes/from.html', ctx)

tasks/views.py
from django.shortcuts import render

# Create your views here.

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to the Home Page</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="home-page">
        <div class="content">
            <h1>Welcome to the Home Page</h1>
            <div class="button-container">
                <a href="{% url 'notes:list' %}" class="nav-button">Go to Notes List</a>
                <a href="{% url 'home' %}" class="nav-button">Go to Task List</a>
            </div>
        </div>
    </div>
</body>
</html>

templates/notes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Note Detail</title>
</head>
<body>
    <h1>Note Detail</h1>
    <button><a href="{% url 'notes:list' %}">Back to list</a></button>
    <button><a href="{% url 'home' %}">Back home</a></button>
    <h3>Note Title: {{ note.notes_title }}</h3>
    <h3>Content: {{ note.content }}</h3>
    <button><a href="{% url 'notes:delete' pk=note.pk %}">Delete</a></button>
</body>
</html>

templates/notes/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Note</title>
</head>
<body>
    <h1>Create Note</h1>
    <form method="post">
        {% csrf_token %}
        <label for="note_title">Note Title</label><br>
        <input type="text" name="note_title" id="note_title"><br>
        <label for="content">Content</label><br>
        <input type="text" name="content" id="content"><br>
        <button type="submit">Create student</button>
    </form>
    <br>
    <button><a href="{% url 'notes:list' %}">Back to list</a></button>
</body>
</html>

templates/notes/list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note List</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="page note-page">
        <div class="content">
            <h1>Note List</h1>
            <div class="button-container">
                <a href="{% url 'notes:create' %}" class="button create-button">Create Note</a>
                {% for notes in note %}
                     <a href="{% url 'notes:detail' pk=note.pk %}"><h3>{{ note.note_title }} </h3></a>
                {% empty %}
                     <h3>No notes</h3>
                {% endfor %}
                <a href="{% url 'home' %}" class="button back-button">Back to Home</a>
            </div>
        </div>
    </div>

</body>
</html>

templates/tasks/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/tasks/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/tasks/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>